# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"
loaderVersion="[43,)"
license="GPL-3.0 License"
issueTrackerURL="https://github.com/grim3212/AssortedDecor"

[[mods]]
modId="assorteddecor"
version="${file.jarVersion}"
displayName="Assorted Decor"
#updateJSONURL=""
displayURL="https://assortedmods.com/decor"
logoFile="logo.png"
authors="Grim3212"
description='''
An assortment of various decorations to improve the look of your Minecraft world.
'''

[[dependencies.assorteddecor]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assorteddecor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
